import type { Metadata } from "next";
import "@/styles/main.css";
import { Toaster } from "sonner";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body>
                {children}
                <Toaster position="bottom-right" />
            </body>
        </html>
    );
}
